"""empty message

Revision ID: 89c5eb1c012f
Revises: 
Create Date: 2022-12-21 23:42:30.785054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89c5eb1c012f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=250), nullable=False),
    sa.Column('subtitle', sa.VARCHAR(length=250), nullable=False),
    sa.Column('date', sa.VARCHAR(length=250), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.Column('img_url', sa.VARCHAR(length=250), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['registered_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###
