"""empty message

Revision ID: d65f0588e1d7
Revises: 
Create Date: 2022-12-20 22:56:41.782211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd65f0588e1d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registered_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.TEXT(length=250),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('subtitle',
               existing_type=sa.TEXT(length=250),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.TEXT(length=250),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.TEXT(length=250),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('img_url',
               existing_type=sa.TEXT(length=250),
               type_=sa.String(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.alter_column('img_url',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(length=250),
               existing_nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(length=250),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(length=250),
               existing_nullable=False)
        batch_op.alter_column('subtitle',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(length=250),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(length=250),
               existing_nullable=False)

    op.drop_table('registered_users')
    # ### end Alembic commands ###
